version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: weekly
    time: "01:00"
    timezone: "Australia/Melbourne"
  open-pull-requests-limit: 20
  reviewers:
  - "purekrome"
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major"]

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    time: "01:00"
    timezone: "Australia/Melbourne"
  open-pull-requests-limit: 20
  reviewers:
  - "purekrome"
